/* ──────────────────────────────────────────────────────────────
   Social Crawlee – Mock Data
   Realistic demo data for dashboard rendering.
   ────────────────────────────────────────────────────────────── */

import {
  Platform,
  JobType,
  JobStatus,
  type Job,
  type DashboardStats,
} from "@/types";

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    datasetId: "ds_a1b2c3d4",
    platform: Platform.INSTAGRAM,
    jobType: JobType.PROFILE,
    status: JobStatus.COMPLETED,
    progress: 100,
    totalItems: 5,
    processedItems: 5,
    input: { usernames: ["nike", "adidas", "puma", "reebok", "underarmour"], maxItems: 5 },
    createdAt: "2026-02-19T10:00:00Z",
    updatedAt: "2026-02-19T10:02:30Z",
    finishedAt: "2026-02-19T10:02:30Z",
  },
  {
    id: "2",
    datasetId: "ds_e5f6g7h8",
    platform: Platform.X,
    jobType: JobType.POSTS,
    status: JobStatus.RUNNING,
    progress: 64,
    totalItems: 50,
    processedItems: 32,
    input: { usernames: ["elonmusk"], daysBack: 3, maxItems: 50 },
    createdAt: "2026-02-19T11:15:00Z",
    updatedAt: "2026-02-19T11:18:00Z",
  },
  {
    id: "3",
    datasetId: "ds_i9j0k1l2",
    platform: Platform.TIKTOK,
    jobType: JobType.COMMENTS,
    status: JobStatus.QUEUED,
    progress: 0,
    totalItems: 100,
    processedItems: 0,
    input: {
      postUrls: ["https://tiktok.com/@user/video/12345"],
      daysBack: 7,
      maxItems: 100,
    },
    createdAt: "2026-02-19T11:30:00Z",
    updatedAt: "2026-02-19T11:30:00Z",
  },
  {
    id: "4",
    datasetId: "ds_m3n4o5p6",
    platform: Platform.FACEBOOK,
    jobType: JobType.PROFILE,
    status: JobStatus.COMPLETED,
    progress: 100,
    totalItems: 10,
    processedItems: 10,
    input: {
      usernames: ["meta", "facebook", "instagram", "whatsapp", "oculus", "threads", "messenger", "workplace", "spark", "pytorch"],
      maxItems: 10,
    },
    createdAt: "2026-02-18T09:00:00Z",
    updatedAt: "2026-02-18T09:05:00Z",
    finishedAt: "2026-02-18T09:05:00Z",
  },
  {
    id: "5",
    datasetId: "ds_q7r8s9t0",
    platform: Platform.INSTAGRAM,
    jobType: JobType.POSTS,
    status: JobStatus.FAILED,
    progress: 23,
    totalItems: 30,
    processedItems: 7,
    input: { usernames: ["private_account_xyz"], daysBack: 7, maxItems: 30 },
    createdAt: "2026-02-18T14:00:00Z",
    updatedAt: "2026-02-18T14:03:00Z",
    finishedAt: "2026-02-18T14:03:00Z",
    errorMessage: "Profile is private. Unable to scrape posts.",
  },
  {
    id: "6",
    datasetId: "ds_u1v2w3x4",
    platform: Platform.X,
    jobType: JobType.COMMENTS,
    status: JobStatus.COMPLETED,
    progress: 100,
    totalItems: 200,
    processedItems: 200,
    input: {
      postUrls: ["https://x.com/user/status/1234567890"],
      daysBack: 1,
      maxItems: 200,
    },
    createdAt: "2026-02-17T08:00:00Z",
    updatedAt: "2026-02-17T08:10:00Z",
    finishedAt: "2026-02-17T08:10:00Z",
  },
  {
    id: "7",
    datasetId: "ds_y5z6a7b8",
    platform: Platform.TIKTOK,
    jobType: JobType.PROFILE,
    status: JobStatus.RUNNING,
    progress: 40,
    totalItems: 20,
    processedItems: 8,
    input: {
      usernames: [
        "charlidamelio", "khaby.lame", "bellapoarch", "addisonre",
        "zachking", "willsmith", "therock", "selenagomez",
        "kyliejenner", "arianagrande", "justinbieber", "billieeilish",
        "travisscott", "lizzo", "dualipa", "badgalriri",
        "shakira", "jlo", "kimkardashian", "kendalljenner",
      ],
      maxItems: 20,
    },
    createdAt: "2026-02-19T12:00:00Z",
    updatedAt: "2026-02-19T12:04:00Z",
  },
  {
    id: "8",
    datasetId: "ds_c9d0e1f2",
    platform: Platform.FACEBOOK,
    jobType: JobType.POSTS,
    status: JobStatus.COMPLETED,
    progress: 100,
    totalItems: 15,
    processedItems: 15,
    input: { usernames: ["NASA"], daysBack: 14, maxItems: 15 },
    createdAt: "2026-02-16T16:00:00Z",
    updatedAt: "2026-02-16T16:08:00Z",
    finishedAt: "2026-02-16T16:08:00Z",
  },
];

export const MOCK_STATS: DashboardStats = {
  totalJobs: 8,
  activeJobs: 2,
  completedJobs: 5,
  failedJobs: 1,
  totalItemsScraped: 277,
  jobsByPlatform: {
    [Platform.INSTAGRAM]: 2,
    [Platform.FACEBOOK]: 2,
    [Platform.X]: 2,
    [Platform.TIKTOK]: 2,
  },
  jobsByType: {
    [JobType.PROFILE]: 3,
    [JobType.POSTS]: 3,
    [JobType.COMMENTS]: 2,
  },
  recentJobs: MOCK_JOBS.slice(0, 5),
};
